// client.http
import dotenv from "dotenv";


@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaWF0IjoxNzU5OTQyNjMxLCJleHAiOjE3NTk5NDMyMzF9.EAhQ6CjPXiwsq-hbvUSn9EXKF4CXcD-Q9IYMYlcOh3k
@baseUrl = http://localhost:4000

### Peticiones sin TOKEN

### Obtener todos los clientes 
GET {{baseUrl}}/api/clientes


### Obtener cliente por ID 
GET {{baseUrl}}/api/clientes/1

### Crear un nuevo cliente 
POST {{baseUrl}}/api/clientes
Content-Type: application/json

{
  "name": "Jaider Quintero",
  "address": "Km 1",
  "phone": "3001234567",
  "email": "jqm@gmail.com",
  "password": "12345678",
  "status": "ACTIVE"
}


### Actualizar un cliente 
PATCH {{baseUrl}}/api/clientes/1
Content-Type: application/json

{
  "name": "Juan Perez Actualizado",
  "address": "Calle 456",
  "phone": "3007654321",
  "email": "juan.perez@example.com",
  "password": "654321",
  "status": "ACTIVE"
}



### Eliminar un cliente físicamente 
DELETE {{baseUrl}}/api/clientes/1



### Eliminar un cliente lógicamente
DELETE {{baseUrl}}/api/clientes/1/logic


### ================== RUTAS CON AUTENTICACIÓN ==================